### ISSUE TITLE
Uncaught (in promise) Unable to detect window.okxwallet should be caught

### ISSUE THREAD

**Issue by Charlie85270** [Conflux-Chain/use-wallet#1]
Hey guys, 

I'm facing an issue when I import any functions from `"@cfxjs/use-wallet-react/ethereum/OKX"` 

<img width="1792" alt="image" src="https://github.com/Conflux-Chain/use-wallet/assets/34569321/2325282c-905c-40f5-a02c-63387a7e136f">

The error is understandable because I don't have the OKX wallet installed. It does the same with Metamask and Fluent if I uninstall both extensions. 

But as the error is uncaught and it's not possible to catch it on my side (it happens on import) the error is always display on development mode. It should be a warning and not an uncatched error. 

Can you caught this error or just display a warning on the console to avoid this screen on development mode ?

**Comment by SSSensational** [comment]
Thanks for your PR. This PR has been released in @cfxjs/use-wallet-react version-0.0.1

**Comment by Charlie85270** [comment]
Thank you @SSSensational , it's possible to deploy a new version (npm package) of the lib with the fix ?
